# Generated by Django 4.1.7 on 2023-03-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='correo',
            field=models.EmailField(default='sin correo', max_length=254),
        ),
        migrations.AddField(
            model_name='customers',
            name='nombre',
            field=models.CharField(default='sin correo', max_length=100),
            preserve_default=False,
        ),
    ]
