# Generated by Django 4.1.7 on 2023-03-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papas_app', '0004_alter_customer_id_alter_order_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='order',
            name='id_order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('id_order', 'customer', 'product')},
        ),
    ]
