# Generated by Django 4.1.7 on 2023-03-26 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papas_app', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papas_app.customer')),
                ('products', models.ManyToManyField(to='papas_app.product')),
            ],
        ),
    ]
