name: Django Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_env.txt

      - name: Run tests
        run: |
          python manage.py test
          test_exit_code=$?
          echo "::set-output name=test_exit_code::$test_exit_code"

      - name: Fail if tests fail
        if: ${{ steps.test.outputs.test_exit_code != 0 }}
        run: exit 1
